### ISSUE TITLE
Make a database table for inputting concert answer scores

### ISSUE THREAD

**Issue by delaneyrae** [devvmh/hackthesymphony#7]
Make a database entry table for inputting concert answer scores--this has to be really easy for KW Symphony to keep up/manage.

**Comment by devvmh** [comment]
@delaneyrae @unlmtdcrtvty @chelseamills This is implemented at http://localhost:8000/scores. I just now pushed a thing that actually tells you the messages.

I'm closing this issue.... but please someone else (probably Chelsea) open another issue with requests on how the table could work better (e.g. better styling, or better messages, or different behaviour, or something). Even just documenting annoyances with using the table would be helpful

**Comment by devvmh** [comment]
OK I'm just reopening this one, I've already thought of suggestions
- Group the answers by question, and make one table per question, so that it's clear what the answers are referring to
- fix the weird opacity on the table in CSS - I think the colours for the striping, hover effects, and green around cells with non-0 scores are all muted and should be more vivid, but there's something making them transparent-ish
- Could someone write up what a more helpful message would be than 'Updated score for mapping #115, which deals with Answer "Yeah!" and Concert "Tenore".'?
- Does the green highlighting on cells with actual numbers help?
- Does the number next to the answer titles on the left side help?
- Does giving the mapping id help?
- Should we have an interface for exporting the values from your database to fixtures? How should we handle exporting database values to fixtures? Maybe this is a question to ask on Wednesday at our meeting with the symphony folks

**Comment by devvmh** [comment]
Left todo:
- More helpful message than 'Updated score for mapping #115, which deals with Answer "Yeah!" and Concert "Tenore".'
- Create an interface for exporting the values from your database to fixtures? How should we handle exporting database values to fixtures?
